###
POST http://localhost:9000/api/usuarios HTTP/1.1
Content-Type: application/json

{
    "nombre" : "Test",
    "apellidos" : "Lnx",
    "puesto" : "Fabricante",
    "email":"test01@tesla.com",
    "password":"123456",
    "isAdmin":true,
    "role":["administrador","editor"],
    "salas":"6244a318a897459420403a9e",
    "status" : false
}

###
GET http://localhost:9000/api/usuarios HTTP/1.1

###
GET http://localhost:9000/api/usuarios/6245e3aada1118b07479161c HTTP/1.1

###
PUT http://localhost:9000/api/usuarios/623ddb9d2fc794ccf62d633 HTTP/1.1
Content-Type: application/json

{
    "nombre" : "José Roberto",
    "apellidos" : "Hernández",
    "puesto" : "Fabricante",
    "usuario" : "CHernandez",
    "status" : false
}

###
DELETE http://localhost:9000/api/usuarios/6245f3205779bf00b00654e2 HTTP/1.1

###
POST http://localhost:9000/api/salas HTTP/1.1
Content-Type: application/json 
Authorization: token jdjdjdjdjdjd
{
    "nombre" : "Game Planet",
    "aforo" : 588,
    "status" : false
}

###
GET http://localhost:9000/api/salas HTTP/1.1

###
POST http://localhost:9000/api/auth  HTTP/1.1
Content-Type: application/json

{
    "email": "ezer@tesla.com",
    "password" :"123456"
}

###
POST url HTTP/1.1
header name: header value

content